---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-endpoint
  labels:
    app: proxy-endpoint
spec:
  selector:
    matchLabels:
      app: proxy-endpoint
  template:
    metadata:
      labels:
        app: proxy-endpoint
    spec:
      containers:
        - image: networkservicemeshci/proxy-endpoint:master
          imagePullPolicy: IfNotPresent
          name: proxy-endpoint
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              value: proxy-endpoint
            #            - name: DLV_LISTEN_PROXY_ENDPOINT
            #              value: :40000
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NSM_LISTEN_ON
              value: tcp://127.0.0.1:6001
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: Directory
