---
name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Install yamllint
        run: pip install --user yamllint
      - name: Run yamllint
        run: ~/.local/bin/yamllint -c .yamllint.yml --strict .
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: fkautz/shell-linter@v1.0.1
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_CONTAINER: golangci/golangci-lint:v1.28.1
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Pull golangci-lint docker container
        run: docker pull ${GOLANGCI_LINT_CONTAINER}
      - name: Run golangci-lint
        run: docker run --rm -v $(pwd):/app -w /app ${GOLANGCI_LINT_CONTAINER} golangci-lint run
  excludeFmtErrorf:
    name: exclude fmt.Errorf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Exclude fmt.Errorf
        run: |
          if grep -r --include=*.go --exclude=*.pb.go fmt.Errorf . ; then
           echo "Please use errors.Errorf (or errors.New or errors.Wrap or errors.Wrapf) as appropriate rather than fmt.Errorf"
           exit 1
          fi
  checkgomod:
    name: check go.mod and go.sum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - run: go mod tidy
      - name: Check for changes in go.mod or go.sum
        run: |
          git diff --name-only --exit-code go.mod || ( echo "Run go tidy" && false )
          git diff --name-only --exit-code go.sum || ( echo "Run go tidy" && false )
  gogenerate:
    name: Check generated files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@master
        with:
          version: '3.8.0'
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install proto-gen-go
        run: go get -u github.com/golang/protobuf/protoc-gen-go@v1.3.3
      - name: Install proto-gen-go
        run: go get github.com/searKing/golang/tools/cmd/go-syncmap
      - name: Generate files
        run: go generate ./...
      - name: Check for changes in generated code
        run: |
          git diff -- '*.pb.go' || ( echo "Rerun go generate ./... locally and resubmit" && false )
          git diff -- '*.gen.go' || ( echo "Rerun go generate ./... locally and resubmit" && false )
  automerge:
    name: automerge
    runs-on: ubuntu-latest
    needs:
      - kind
    if: github.actor == 'nsmbot' && github.base_ref == 'master' && github.event_name == 'pull_request'
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Fetch master
        run: |
          git remote -v
          git fetch --depth=1 origin master
      - name: Only allow go.mod and go.sum changes
        run: |
          find . -type f ! -name 'go.mod' ! -name 'go.sum' -exec git diff --exit-code origin/master -- {} +
      - name: Automerge nsmbot PR
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: nsmbot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.4.0
        with:
          config: cluster-config.yaml
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
          github-token: ${{ github.token }}
      - uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 0.4.1
      - name: Check kind cluster
        run: |
          docker build cmd/nse -t networkservicemeshci/nse:master
          docker build cmd/fake-nsmgr -t networkservicemeshci/fake-nsmgr:master
          docker build cmd/proxy-client -t networkservicemeshci/proxy-client:master
          docker build cmd/proxy-endpoint -t networkservicemeshci/proxy-endpoint:master
          kind load docker-image networkservicemeshci/nse:master
          kind load docker-image networkservicemeshci/fake-nsmgr:master
          kind load docker-image networkservicemeshci/proxy-client:master
          kind load docker-image networkservicemeshci/proxy-endpoint:master
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Integration tests
        run: |
          gotestsum --format standard-verbose -- -race -short $(go list ./...)
